### ISSUE TITLE
Add `parse(TimeSpan, ...)` support

### ISSUE THREAD

**Issue by hannahilea** [beacon-biosignals/TimeSpans.jl#35]
E.g., for Beacon-internal use case of parsing `str = "[start_ns,stop_ns)"`

**Comment by ararslan** [comment]
This was actually proposed and implemented before: https://github.com/beacon-biosignals/TimeSpans.jl/pull/17

**Comment by hannahilea** [comment]
...it sure was! And it was closed for good reason, so I'm going to close this one too, I guess. 😂

**Comment by omus** [comment]
I forgot about that myself. Still was good to make this issue though as it builds up a collection of use cases
