### ISSUE TITLE
Backport invert_spans

### ISSUE THREAD

**Issue by mich11** [beacon-biosignals/TimeSpans.jl#37]
It'd be helpful to backport `invert_spans` from #36 to TimeSpans v0.2 to maintain compatibility with Onda. 

[Description of the version conflict between Onda and TimeSpans v0.3](https://github.com/beacon-biosignals/Onda.jl/issues/123)

**Comment by ararslan** [comment]
Closed by #38. This is now available in TimeSpans v0.2.8.
