### ISSUE TITLE
Tag 1.0?

### ISSUE THREAD

**Issue by glennmoy** [beacon-biosignals/TimeSpans.jl#59]
The package hasn't been actively updated in a few months and the API seems to be largely feature complete? At least the development seems to have stabilised.

With that in mind it may be time to tag 1.0?

**Comment by palday** [comment]
Also allows us to distinguish bug fixes vs. feature releases.

**Comment by kleinschmidt** [comment]
We've (@omus, @ericphanson, @glennmoy , @MKVatinyan and I) discussed this internally and think it's a good idea.  Will require compat bumps across the board but probably worth it and TimeSpans has been very stable at this point.

**Comment by kleinschmidt** [comment]
I think the scope of this includes bumping all downstream dependencies in addition to actually tagging/releasing 1.0
